appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ppG1utDJz9SC3HohcBT/Aj7FpjBF1s3GG0MnadLCHNQzjUmOzsKogI7iX1YQY1lgUFSiy6Ca8K1zO8YPFwmelRPm5LKPnkG/fqj52zCzaZ8fvV1tr1STOwF/FlszCN2vwcQjzUg88+RrUu8riOOQauAbzZ5sOAh0Rf/AUe1iLzlliFmYOn66VRpNRiFJ/tzwIkQi37AqN9YvlDwSESnGbeaCUQpsco4RIuY6CtFqarSghSZ8u+UJthYGBIpCieHdvopwIyEYB1w5GwAKVL1mWFxetKE8zx7GhtHB5VG6+mBU1uMSHa7+JWV37jpVIZkz9f+24I+wW1TVLGDuv7cuHbYWKr05wUaGFhlp5xMinaveUytxMCh5/crz8LLtc2tcxuoQGuS1DpPAZTSmiXnm3FiXlDYM2cUIW12ZtaQ+OSiSa4la71dmiiAmrb8TIKJQf8RQ9Wr8cRkMMBn5EokT/HSZhX/VdH5O/C6E/2J42cGJJH/wuCFtq3965qFauo5Kb08trcfiJndtrq+eVpULKObY1hf8uEIOjyDDWsLOUnzX5PxJcnYRRDixCoFxbvaR2uVWyl/tzCJ4/c7moO6FI9I2DT1Or6dElco9v0pZpkauLHPyzppSFvChsIjMdsuoqIJdosC7mxWNu5jKlqPNbJpF+9Wghn00maICfithbX0=}
conda_forge_output_validation: true
